"""Adding models

Revision ID: 3147fd97b972
Revises: 82ffa14623b2
Create Date: 2024-06-26 04:23:41.692471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3147fd97b972'
down_revision: Union[str, None] = '82ffa14623b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pastes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('syntax_highlight', sa.Boolean(), nullable=False),
    sa.Column('exposure', sa.Enum('PUBLIC', 'PRIVATE', 'UNLISTED', name='exposure'), nullable=False),
    sa.Column('category', sa.Enum('PROGRAMMING', 'CONFIGURATION_FILES', 'SCRIPTS', 'DOCUMENTATION', 'LOGS', 'DATA', 'SNIPPETS', 'NOTES', 'TEXT', 'TEMPLATES', 'SECURITY', 'MISCELLANEOUS', name='pastecategory'), nullable=False),
    sa.Column('expiration', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('password_disabled', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('burn_after_read', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pastes_tags',
    sa.Column('paste_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paste_id'], ['pastes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastes_tags')
    op.drop_table('pastes')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
