"""User password -> hashed_password

Revision ID: 48781ab2806b
Revises: 7b69e006fd18
Create Date: 2024-07-07 17:19:55.484590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48781ab2806b'
down_revision: Union[str, None] = '7b69e006fd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pastes', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.alter_column('users', 'password', new_column_name='hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password', nullable=False)
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'pastes', type_='unique')
    # ### end Alembic commands ###
