"""Adding TimestampMixin

Revision ID: c6a370ecaf74
Revises: d510508974a6
Create Date: 2024-06-16 20:18:00.600621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a370ecaf74'
down_revision: Union[str, None] = 'd510508974a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('pastes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'pastes', ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'pastes', type_='unique')
    op.drop_column('pastes', 'updated_at')
    op.drop_column('pastes', 'created_at')
    # ### end Alembic commands ###
